name: VoiceRelaySwiftUI
options:
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    PRODUCT_NAME: VoiceRelaySwiftUI
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  VoiceRelaySwiftUI:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.voicerelayswiftui
    preBuildScripts:
      - name: Copy .env into .app (dev)
        script: |
          cp -f "${PROJECT_DIR}/../../.env" "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/.env" 2>/dev/null || true
        basedOnDependencyAnalysis: false
