[package]
name = "tui-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
tokio = { version = "1.42", features = ["full"] }
cpal = "=0.13.5"
hound = "3.5"
reqwest = { version = "0.12", features = ["multipart", "stream", "json"] }
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
