[package]
name = "stt-clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
cpal = "=0.13.5"
hound = "3.5"
reqwest = { version = "0.12", features = ["multipart", "stream", "json"] }
arboard = "3.4"
crossterm = "0.28"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rdev = "0.5"
ctrlc = "3.4"
async-trait = "0.1"
global-hotkey = "0.5"

