name: WalkingComputer
options:
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_NAME: WalkingComputer
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    INFOPLIST_KEY_UIStatusBarHidden: YES
    INFOPLIST_KEY_UIRequiresFullScreen: YES
    INFOPLIST_KEY_UIViewControllerBasedStatusBarAppearance: NO
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
targets:
  WalkingComputer:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        UIStatusBarHidden: true
        UIRequiresFullScreen: true
        UIViewControllerBasedStatusBarAppearance: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen: {}
        NSMicrophoneUsageDescription: Walking Computer needs microphone access for voice recording
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.walkingcomputer
    preBuildScripts:
      - name: Copy .env file
        script: |
          cp -f "${PROJECT_DIR}/.env" "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/.env" 2>/dev/null || true
        basedOnDependencyAnalysis: false

  WalkingComputerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: WalkingComputer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.walkingcomputer.tests
        GENERATE_INFOPLIST_FILE: YES