name: VoiceAgent
options:
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_NAME: VoiceAgent
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    INFOPLIST_KEY_UIStatusBarHidden: YES
    INFOPLIST_KEY_UIRequiresFullScreen: YES
    INFOPLIST_KEY_UIViewControllerBasedStatusBarAppearance: NO
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
targets:
  VoiceAgent:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        UIStatusBarHidden: true
        UIRequiresFullScreen: true
        UIViewControllerBasedStatusBarAppearance: false
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.voiceagent